// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "new-york": {
    "accordion": {
      name: "accordion",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/accordion.tsx"],
      component: React.lazy(() => import("@/components/ui/accordion.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert": {
      name: "alert",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/alert.tsx"],
      component: React.lazy(() => import("@/components/ui/alert")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["components/ui/alert-dialog.tsx"],
      component: React.lazy(() => import("@/components/ui/alert-dialog.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/aspect-ratio.tsx"],
      component: React.lazy(() => import("@/components/ui/aspect-ratio.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },

    "label-demo": {
      name: "label-demo",
      type: "registry:example",
      registryDependencies: ["label"],
      files: ["/components/(docs)/componentpreview/label-demo.tsx"],
      component: React.lazy(() => import("@/components/(docs)/componentpreview/label-demo")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  
    "header-demo": {
      name: "header-demo",
      type: "registry:block",
      registryDependencies: ["header"],
      files: ["/src/components/(docs)/(components)/header.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/header")),
      source: "src/components/(docs)/(components)/header.tsx",
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
    "hero1-demo": {
      name: "hero1-demo",
      type: "registry:block",
      registryDependencies: ["hero1"],
      files: ["/src/components/(docs)/(components)/hero1.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/hero1")),
      source: "src/components/(docs)/(components)/hero1.tsx",
      category: "hero-section",
      subcategory: "hero",
      chunks: []
    },
    "hero2-demo": {
      name: "hero2-demo",
      type: "registry:block",
      registryDependencies: ["hero2"],
      files: ["/src/components/(docs)/(components)/hero2.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/hero2")),
      source: "src/components/(docs)/(components)/hero2.tsx",
      category: "hero-section",
      subcategory: "hero",
      chunks: []
    },

    "brands-demo": {
      name: "brands-demo",
      type: "registry:block",
      registryDependencies: ["brands"],
      files: ["/src/components/(docs)/(components)/brands.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/brands")),
      source: "src/components/(docs)/(components)/brands.tsx",
      category: "brands",
      subcategory: "brands",
      chunks: []
    },
    "blogs-demo": {
      name: "blogs-demo",
      type: "registry:block",
      registryDependencies: ["blogs"],
      files: ["/src/components/(docs)/(components)/blogs.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/blogs")),
      source: "src/components/(docs)/(components)/blogs.tsx",
      category: "blogs",
      subcategory: "blogs",
      chunks: []
    },
    "testimonial-demo": {
      name: "testimonial-demo",
      type: "registry:block",
      registryDependencies: ["blogs"],
      files: ["/src/components/(docs)/(components)/testimonial.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/testimonial")),
      source: "src/components/(docs)/(components)/blogs.tsx",
      category: "blogs",
      subcategory: "blogs",
      chunks: []
    },
    "footer-demo": {
      name: "footer-demo",
      type: "registry:block",
      registryDependencies: ["blogs"],
      files: ["/src/components/(docs)/(components)/footer.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/footer")),
      source: "src/components/(docs)/(components)/footer.tsx",
      category: "blogs",
      subcategory: "blogs",
      chunks: []
    },
    "teams-demo": {
      name: "teams-demo",
      type: "registry:block",
      registryDependencies: ["teams"],
      files: ["/src/components/(docs)/(components)/teams.tsx"],
      component: React.lazy(() => import("@/components/(docs)/(components)/teams")),
      source: "src/components/(docs)/(components)/teams.tsx",
      category: "teams",
      subcategory: "teams",
      chunks: []
    },
  },
  

    "avatar": {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/avatar.tsx"],
      component: React.lazy(() => import("@/components/ui/avatar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "authentication-01": {
      name: "authentication-01",
      type: "registry:block",
      style:"new-york",
      registryDependencies: ["button","card","input","label"],
      files: ["components/(docs)/authentication-01.tsx"],
      component: React.lazy(() => import("@/components/(docs)/authentication-01.tsx")),
      source: "src/components/(docs)/authentication-01.tsx",
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },

}