// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "new-york": {
    "accordion": {
      name: "accordion",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/accordion.tsx"],
      component: React.lazy(() => import("@/components/ui/accordion.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert": {
      name: "alert",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/alert.tsx"],
      component: React.lazy(() => import("@/components/ui/alert")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["components/ui/alert-dialog.tsx"],
      component: React.lazy(() => import("@/components/ui/alert-dialog.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/aspect-ratio.tsx"],
      component: React.lazy(() => import("@/components/ui/aspect-ratio.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "label-demo": {
      name: "label-demo",
      type: "registry:example",
      registryDependencies: ["label"],
      files: ["/components/(docs)/componentpreview/label-demo.tsx"],
      component: React.lazy(() => import("@/components/(docs)/componentpreview/label-demo")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["components/ui/avatar.tsx"],
      component: React.lazy(() => import("@/components/ui/avatar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "authentication-01": {
      name: "authentication-01",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: ["components/(docs)/authentication-01.tsx"],
      component: React.lazy(() => import("@/components/(docs)/authentication-01.tsx")),
      source: "src/components/(docs)/authentication-01.tsx",
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
}
}